
version: '3'

services:
  goweb:
    container_name: goweb
    volumes:
      - ./backend:/go/src/app
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    tty: true
    environment:
      WORDPRESS_DB_HOST: gowebdb:3306
      WORDPRESS_DB_USER: gowebdb
      WORDPRESS_DB_PASSWORD: gowebdb
      WORDPRESS_DB_NAME: gowebdb
      # GO111MODULE: "off"
    # command: gin -i run
    # command: go run main.go
    # command: bash -c "/bin/bash"
    ports:
      - "3000:3000"
    depends_on:
      - gowebdb
    platform: linux/amd64

  gowebdata:
    container_name: gowebdata
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: gowebdata
      MYSQL_USER: gowebdata
      MYSQL_PASSWORD: gowebdata
      TZ: 'Asia/Tokyo'
    ports:
      - "3310:3306"
    volumes:
      # - db_data:/var/lib/mysql
      - db_data:/var/lib/mysql

volumes:
  db_data:
